# Generated by Django 5.1.2 on 2024-10-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_snippet_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[('py', 'Python'), ('js', 'Javascript'), ('cpp', 'C++'), ('php', 'PHP')], max_length=30),
        ),
    ]
