# Generated by Django 5.1.2 on 2024-10-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_snippet_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='public',
            field=models.BooleanField(choices=[(True, 'Public'), (False, 'Private')], default=True),
        ),
    ]
